SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(PRICE*SALES) TOTAL_SALES
from BOOK a
join AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
join BOOK_SALES c on a.BOOK_ID = c.BOOK_ID
where SALES_DATE between '2022-01-01' and '2022-01-31'
group by  AUTHOR_ID, AUTHOR_NAME, CATEGORY
order by a.AUTHOR_ID, CATEGORY desc