name: Move files under auto_upload

on:
  push:
    branches: [ "main" ]

jobs:
  move:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow committing with GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Move 백준/* into auto_upload/
        shell: bash
        run: |
          set -e

          moved=false

          # 이미 auto_upload/ 또는 .github/ 아래는 스킵
          # "백준/"으로 시작하는 모든 경로(파일/폴더)를 대상으로 이동
          while IFS= read -r path; do
            [ -z "$path" ] && continue
            case "$path" in
              auto_upload/*|.github/*|.git/*) continue ;;
            esac

            # 디렉터리/파일 모두 처리
            dest="auto_upload/$path"
            mkdir -p "$(dirname "$dest")"
            git mv -f -- "$path" "$dest" || true
            moved=true
          done < <(git ls-files | grep -E '^백준/')

          # (선택) 루트에 떠 있는 단일 소스 파일도 같이 정리하고 싶으면 아래 주석 해제
          # while IFS= read -r path; do
          #   [ -z "$path" ] && continue
          #   case "$path" in
          #     auto_upload/*|.github/*|.git/*) continue ;;
          #   esac
          #   dest="auto_upload/$path"
          #   mkdir -p "$(dirname "$dest")"
          #   git mv -f -- "$path" "$dest" || true
          #   moved=true
          # done < <(git ls-files | grep -E '^[^/]+\.(py|cpp|java|md)$')

          if [ "$moved" = true ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: auto-move 백준/* under auto_upload/"
            git push
          else
            echo "Nothing to move."
          fi
